### ISSUE TITLE
Works great.. one little bug :)

### ISSUE THREAD

**Issue by cowboysdude** [ianperrin/MMM-ModuleScheduler#1]
Having it running on 4 modules... it shuts them all down.  
1.  stop at 10PM
2.  stop at 10:30pm
3.  stop at 11PM
4.  stop at 11pm

It shuts them all off at 10 pm ;)

**Comment by ianperrin** [comment]
Can you share the module_scheduler option you have defined for in config.js for each module and if possible the output of the log ('pm2 logs mm')?

**Comment by cowboysdude** [comment]
Ian I'm sorry I didn't but I assure you I had the module setup correctly.  You have since fixed it and the new update fixed it!! Thank you so much for your time and attention!!!!  It's VERY appreciated!!
