### ISSUE TITLE
Two different classes in MMM-ModuleScheduler.

### ISSUE THREAD

**Issue by lunaticasylum** [ianperrin/MMM-ModuleScheduler#10]
Hi Ian,

A great thank for your module. I love it. 

I would like to have « dimined » but also « daytime_scheduler «  in MMM-ModuleScheduler. 
Is there a way to set up at least 2 ddiffertns classes in the same module ? 

I have been tried but no succes.

**Comment by ianperrin** [comment]
@lunaticasylum - you may have already worked this out, but this should be possible by doing the following...
````
    classes: 'dimmed daytime_scheduler',
````

**Comment by lunaticasylum** [comment]
Thanks Ian. 

Yann
