### ISSUE TITLE
MonitorON issue

### ISSUE THREAD

**Issue by andrew16x** [ianperrin/MMM-ModuleScheduler#13]
Hello,

I was wondering if you could help me figure this out. The MonitorOFF/ON schedule works OK with one caveat. 

When the OFF signal is triggered, I get the no signal box floating around the screen, meaning there is no input on that HDMI port. However after a couple of minutes, the TV switches off completely, and so if the MonitorON is triggered it doesn't have any effect, it won't turn the TV back on. MonitorON only works within that short period while the HDMI signal is in "standby" (when the no signal box is floating).

Is there a way to wake up the TV from the OFF state at all?

Many thanks and best regards.

**Comment by ianperrin** [comment]
@andrew16x - sorry, I'm not aware of any way to power back on the monitor in these situations. You could try the MagicMirror forums and if you do find a software solution do let me know and I'll see if it's possible to incorporate. Sorry.
