### ISSUE TITLE
It doesn't work. 

### ISSUE THREAD

**Issue by Canguingo** [ianperrin/MMM-ModuleScheduler#18]
Hi, this module doesn't work. I might be doing something wrong, I just followed the instructions. 

this is the code in my config file:
````
{
           	module: 'MMM-google-route',
            	position: 'top_right',
            	classes: 'scheduler',
		config: {
		// DISPLAY THE CALENDAR BETWEEN 07:50 and 21:00 from Mondays to WEDNESDAYS
		module_schedule: {from: '50 7 * * 1-3', to: '15 21 * * 1-3' },
                key: '[keynumber]',
                directionsRequest:{
                    origin: 'Maarssen',
                    destination: 'Schiphol'
                }
````
any idea what could have gone wrong?

**Comment by ianperrin** [comment]
@Canguingo

A couple of quick things to check.

Did you also add the following to your config file?
````
    {
        module: 'MMM-ModuleScheduler'
    },
````

Did you run `npm install --production` after pulling the module to install the dependencies?

If you’ve done all of the above, can you set the `debug` option and share the output of the logs?

**Comment by Canguingo** [comment]
Great!! It works! I indeed forgot to add that { }, part.. thank you very much! great module!
