### ISSUE TITLE
Confusion with Global schedule when using one class

### ISSUE THREAD

**Issue by AlexDunn7** [ianperrin/MMM-ModuleScheduler#22]
Hello,

I'll give you an example of how I want to use this module. Bit more complex in the config because I've done each day with different times.

6:45AM - Monitor turns on + Display clock module ONLY
7:00AM - Display all modules bar the clock + Hide clock module
8:00AM - Monitor turns off + Hide clock module
4:00PM - Turn monitor on + Display all modules bar the clock
9:45PM - Hide all modules + Display clock
10:00PM - Hide all modules + Monitor turns off

I tried doing this by setting all modules bar the clock with the class "daytime_schedular" but it seems like you can only have one global schedular per class as when I have the config as shown in the example it shows no modules and it is 19:47 on a Tuesday when it should be displaying. I don't expect you to write all the code out but if you could point where I might be able to find a solution to my complex problem. Thanks :)
`global_schedule: [
{from: '00 10 * * 1', to: '45 22 * * 1', groupClass: 'daytime_scheduler'},
{from: '00 10 * * 2,4', to: '15 22 * * 2,4', groupClass: 'daytime_scheduler'},
{from: '20 07 * * 3', to: '45 22* * 3', groupClass: 'daytime_scheduler'},
{from: '20 07 * * 5', to: '15 23* * 5', groupClass: 'daytime_scheduler'},
{from: '30 10 * * 6', to: '15 23 * * 6', groupClass: 'daytime_scheduler'},
{from: '30 10 * * 7', to: '45 22* * 7', groupClass: 'daytime_scheduler'},
],
`
**Code for monitor ON/OFF**

`            notification_schedule: [
                {notification: 'REMOTE_ACTION', schedule: '50 09 * * 1', payload: {action: "MONITORON"}},
                {notification: 'REMOTE_ACTION', schedule: '00 23 * * 1', payload: {action: "MONITOROFF"}},
                {notification: 'REMOTE_ACTION', schedule: '50 09 * * 2-4', payload: {action: "MONITORON"}},
                {notification: 'REMOTE_ACTION', schedule: '20 22 * * 2-4', payload: {action: "MONITOROFF"}},
                {notification: 'REMOTE_ACTION', schedule: '10 7 * * 3', payload: {action: "MONITORON"}},
                {notification: 'REMOTE_ACTION', schedule: '00 23 * * 3', payload: {action: "MONITOROFF"}},
                {notification: 'REMOTE_ACTION', schedule: '10 7 * * 5', payload: {action: "MONITORON"}},
                {notification: 'REMOTE_ACTION', schedule: '30 23 * * 5', payload: {action: "MONITOROFF"}},
                {notification: 'REMOTE_ACTION', schedule: '20 10 * * 6', payload: {action: "MONITORON"}},
                {notification: 'REMOTE_ACTION', schedule: '30 23 * * 6', payload: {action: "MONITOROFF"}},
                {notification: 'REMOTE_ACTION', schedule: '20 10 * * 7', payload: {action: "MONITORON"}},
                {notification: 'REMOTE_ACTION', schedule: '23 00 * * 7', payload: {action: "MONITOROFF"}},

            ]`

**Code for clock** 

`module_schedule: {from: '50 09 * * 1,2,4', to: '45 22 * * 1,2,4' },
module_schedule: {from: '10 07 * * 3,5', to: '20 07 * * 3,5' },
module_schedule: {from: '20 10 * * 6,7', to: '30 10 * * 6,7' },

module_schedule: {from: '45 22 * * 1,3,7', to: '23 00 * * 1,3,7' },
module_schedule: {from: '15 22 * * 2,4', to: '30 22 * * 2,4' },
module_schedule: {from: '15 23 * * 5,6', to: '30 23 * * 5,6' },`

**Comment by ianperrin** [comment]
Hi @AlexDunn7 - did you manage your solve the problem? If so can you share the solution?
