### ISSUE TITLE
Sending a notification at midday instead of midnight

### ISSUE THREAD

**Issue by AlexDunn7** [ianperrin/MMM-ModuleScheduler#23]
[11:49:35.372] [LOG]    MMM-ModuleScheduler will next send SEND_NOTIFICATION to PAGE_CHANGED at Mon Jan 27 2020 22:45:00 GMT+0000 (GMT) based on "45 22 * * 1"

**Comment by ianperrin** [comment]
@AlexDunn7 the log you have shared is an informational message stating when the notification with next be sent.

Can you share your config and a little more detail about the issue you are experiencing?

**Comment by ianperrin** [comment]
I was unable to reproduce this error and as it has been some time since it was reported I am going to close the issue.

If you are still experiencing the error, please do re-open the issue. Thanks
