### ISSUE TITLE
Dim level not going back to normal

### ISSUE THREAD

**Issue by jseidman95** [ianperrin/MMM-ModuleScheduler#26]
Having another issue here, the dimLevel works to dim the modules but doesn't go back to normal after.  Im using the config
```
                        module: 'MMM-ModuleScheduler',
                        config: {
                                global_schedule: [
                                        {from: '0 7 * * *', to: '0 21 * * *', dimLevel: '40'},
                                ],
                        }
```
and after 7:00 AM my modules don't undim

**Comment by LilithDarkmoon** [comment]
I'm also having this issue. I've tried it both with a global schedule:
```
				global_schedule: [
					{ from: "0 6 * * *", to: "00 23 * * *", groupClass: "day" },
					{ from: "0 6 * * *", to: "00 23 * * *", groupClass: "night", dimLevel: "25" },
				]
```
and individual:
`module_schedule: { from: "0 6 * * *", to: "00 23 * * *", dimLevel: "25" },`

With some digging, it appears that the `setModuleDisplay` function for the action `SHOW_MODULE` is not taking into account that the module is already shown. I added the following code after line 110 in `MMM-ModuleScheduler.js`:

```
			if (moduleDiv) {
				moduleDiv.style.filter = "brightness(100%)";
				Log.log(self.name + " setting " + module.identifier + " to " + brightness + "%" );
			}
```

It's the same code from the `DIM_MODULE`—I'm certain there's a more elegant way to do this, but hopefully it helps with fixing the bug.

**Comment by ianperrin** [comment]
@LilithDarkmoon / @jseidman95 I have not been able to reproduce this issue using the unmodified version of the module.

If this is still an issue for you, please re-open the issue and post the output of the log on the Raspberry Pi and the browser (removing any sensitive information first)? Thanks
