### ISSUE TITLE
Limited number of schedule array equals 16.

### ISSUE THREAD

**Issue by Bernard-h** [ianperrin/MMM-ModuleScheduler#28]

**Comment by Bernard-h** [comment]
{
  module: 'MMM-MyGarbage',
  position: 'top_right',
  header: 'Container',
  classes: 'scheduler',
  config: {
	module_schedule: [{from: '0 7 * * *', to: '10 7 * * *'},{from: '20 7 * * *', to: '30 7 * * *'},{from: '40 7 * * *', to: '50 7 * * *'},{from: '0 8 * * *', to: '10 8 * * *'},{from: '20 8 * * *', to: '30 8 * * *'},{from: '40 8 * * *', to: '50 8 * * *'},{from: '0 9 * * *', to: '10 9 * * *'},{from: '20 9 * * *', to: '30 9 * * *'},{from: '40 9 * * *', to: '50 9 * * *'},{from: '0 10 * * *', to: '10 10 * * *'},{from: '20 10 * * *', to: '30 10 * * *'},{from: '30 10 * * *', to: '0 18 * * *'},{from: '0 18 * * *', to: '10 18 * * *'},{from: '20 18 * * *', to: '30 18 * * *'},{from: '40 18 * * *', to: '50 18 * * *'},{from: '0 19 * * *', to: '10 19 * * *'},{from: '20 19 * * *', to: '30 19 * * *'},{from: '40 19 * * *', to: '50 19 * * *'},{from: '0 20 * * *', to: '10 20 * * *'},{from: '20 20 * * *', to: '30 20 * * *'},{from: '40 20 * * *', to: '50 20 * * *'},{from: '0 21 * * *', to: '10 21 * * *'},{from: '20 21 * * *', to: '30 21 * * *'},{from: '40 21 * * *', to: '50 21 * * *'},{from: '0 22 * * *', to: '10 22 * * *'},{from: '20 22 * * *', to: '30 22 * * *'},{from: '40 22 * * *', to: '50 22 * * *'},{from: '0 23 * * *', to: '10 23 * * *'},{from: '20 23 * * *', to: '30 23 * * *'},{from: '30 23 * * *', to: '0 7 * * *'}],	
	  alert: 4,
          weeksToDisplay: 1,
          limitTo: 2,
          fade: false,
          dateFormat: "dddd D MMMM",
          fadePoint: 0.25
  }
},

**Comment by ianperrin** [comment]
@Bernard-h - it looks like you've closed the issue so hopefully you've found a solution.

In the email notification for the issue I saw you have a lot of schedules defined in the `module_schedule` option to show and hide the module every 10 minutes.

I've not  tried using that many schedules in one configuration so can't say whether there is a limit. 

However, you might like to try amending the cron expressions using `list` and `range` values to simplify the configuration.

For example to display the module at [0, 20, and 40 minutes past every hour from 7am through 10am](https://crontab.guru/#0,20,40_7-10_*_*_*) and hide it at [10, 30, and 50 minutes past every hour from 7am through 10am](https://crontab.guru/#10,30,50_7-10_*_*_*) you could try the following configuration:

`module_schedule: [{from: '0,20,40 7-10 * * *', to: '10,30,50 7-10 * * *'}]`

In this schedule the hours (7-10) are specified as a `range` of values, where as the minutes (0,20,40 or 10,30,50) are specified in a `list`.

Hope this helps.
