### ISSUE TITLE
It's really weird when I using Module Scheduler on the Fullscreen module

### ISSUE THREAD

**Issue by yoshiesk** [ianperrin/MMM-ModuleScheduler#32]
Hi, it is so weird, I not sure it is a bug or not

I'm using MMM-GooglePhotos's module as fullscreen_below, everything is fine. but when I set Module Scheduler as an individual,

the whole GooglePhoto module would move up to the top. but the Google Photo still follows the time I set. Just entire module move to the top of the screen

but if I remove the Module Scheduler in the block then Google Photo is working fine.

below is my code in the config.js

		{
			module: 'MMM-ModuleScheduler',
			config: {
				// SHOW MODULES WITH THE CLASS 'daytime_scheduler' AT 06:00 AND HIDE AT 22:00 EVERY DAY
				schedulerClass: "Travis-Photo",
				animationSpeed: "2000",
				uselock: "false"
				//global_schedule: {from: '*/1 */1 * * *', to: '*/2 */1 * * *', groupClass: 'Travis1'},
			}
		},

		{
			module: "MMM-GooglePhotos",
			position: "fullscreen_below",
			classes: "Travis-Photo",
			config: {
				module_schedule:{from: '1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59 * * * *', to: '0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,40,42,44,46,48,50,52,54,56,58 * * * *'},
				albums: ["MagicMirror-Livingroom"], // Set your album name. like ["My wedding", "family share", "Travle to Paris"]
				updateInterval: 1000 * 60, // minimum 10 seconds.
				sort: "new", // "old", "random"
				uploadAlbum: null, // Only album created by `create_uploadable_album.js`.
				condition: {
					fromDate: null, // Or "2018-03", RFC ... format available
					toDate: null, // Or "2019-12-25",
					minWidth: null, // Or 400
					maxWidth: null, // Or 8000
					minHeight: null, // Or 400
					maxHeight: null, // Or 8000
					minWHRatio: null,
					maxWHRatio: null,
					// WHRatio = Width/Height ratio ( ==1 : Squared Photo,   < 1 : Portraited Photo, > 1 : Landscaped Photo)
					
				},
				showWidth: 1080, // These values will be used for quality of downloaded photos to show. real size to show in your MagicMirror region is recommended.
				showHeight: 1920,
				timeFormat: "YYYY/MM/DD HH:mm", // Or `relative` can be used.
				
			}
		},

![Image 4](https://user-images.githubusercontent.com/9322628/125802062-ac4ef1f6-2f82-4d70-8e0b-a3d537adcd97.png)

**Comment by hermanho** [comment]
I have the issue recently. I found that it is caused by a css filter from MMM-ModuleScheduler that will cause a wrong position in child div.
![2022-11-14_22-35-04](https://user-images.githubusercontent.com/2337380/201782584-ac8ac676-beaf-45b7-9ded-91bb91d3ffa1.png)

There has an answer from stackoverflow.
https://stackoverflow.com/a/52937920/2352341

I am trying to figure out to modify some css in MMM-GooglePhotos if it works.
