### ISSUE TITLE
Remove a module after a specific year, month, date and  time?

### ISSUE THREAD

**Issue by lkthomas** [ianperrin/MMM-ModuleScheduler#33]
I want to remove a countdown module after a specific year, month, date, and time, how should I do a one-off removal?

**Comment by ianperrin** [comment]
unfortunately, MMM-ModuleScheduler Doesn’t currently support this as it is based on cron expressions which don’t include the option to trigger schedules based on years.

it’s also worth noting that MMM-ModuleScheduler only controls the display of your modules by hiding and showing them in the mirror. It doesn’t actually remove them from the config file.

I’d therefore suggest manually removing modules from the config file if you no longer require them after a specific date,
