### ISSUE TITLE
If I run it with the MMM-BackgroundSlideshow module specified as a class, it doesn't work properly.

### ISSUE THREAD

**Issue by starsirius9** [ianperrin/MMM-ModuleScheduler#34]
When starting the module, it disappears during fading the background image. And it does not appear on the screen.

**Comment by ianperrin** [comment]
Hi @starsirius9 

thanks for taking the  time to share your issue. I’ve not used the module you mention before so would need some time to look into this.

could you share your config and any relevant output in the logs (removing sensitive info first) ?

Thanks

**Comment by starsirius9** [comment]
{
			module: 'MMM-ModuleScheduler',
			config: {
				// SHOW MODULES WITH THE CLASS 'daytime_scheduler' AT 8:00 AND HIDE AT 22:00 EVERY DAY
				global_schedule: {from: '00 8 * * *', to: '00 22 * * *', groupClass: 'daytime_Mirror'},
				// SHOW MODULES WITH THE CLASS 'nighttime_scheduler' AT 22:00 AND HIDE AT 8:00 EVERY DAY
				global_schedule: {from: '00 22 * * *', to: '00 8 * * *', groupClass: 'nighttime_Mirror'},
			}
		},
		{
			module: 'MMM-BackgroundSlideshow',
			position: 'fullscreen_below',
                        classes: 'daytime_Mirror'
			config: {
				imagePaths: ['/home/pi/Pictures/'],
				backgroundSize: 'contain',
				maxWidth: "100%",
				maxHeight: "100%",
				backgroundPosition: 'left',
				gradientDirection: 'horizontal',
				horizontalGradient: [ "rgba(0, 0, 0, 0) 80%", "rgba(0, 0, 0, 0.75) 100%" ],
				slideshowSpeed: '600000',
				transitionImages: true,
				randomizeImageOrder: true
			}
		},
		{
			module: 'MMM-DigClock',
			position: "upper_third",
			classes: 'nighttime_Mirror',
			config: {
				showDate: true,
				showWeek: false,
				dateFormat: "LL, dddd",
				timezone: "Asia/Seoul"
			}
		},

**Comment by starsirius9** [comment]
MMM-DigClock Module is good operation. But MMM-BackgroundSlideshow Module disappear on the screen. I tested by changing the time. (ex. daytime 8:00 ~ 8:10, night time 8:10 ~ 8:20 or daytime 8:10 ~ 8:20,  nighttime 8:00 ~ 8:10 // daytime to nighttime, nighttime to daytime)

**Comment by ianperrin** [comment]
Hi 

are you still experiencing this issue?

if so, try to make sure your cron expressions are valid and the config file is correctly formatted (looks like you’re missing a comma after `classes: 'daytime_Mirror'`

with that sorted, set the debug option to true for MMM-ModuleScheduler and review the output in the logs. It should state how the schedules have been interpreted with info about when modules will hide/show
