### ISSUE TITLE
Module not loading until next scheduled "from" time

### ISSUE THREAD

**Issue by Fishie20** [ianperrin/MMM-ModuleScheduler#46]
Hi all,

Not sure if this is user error or a bug/feature.  I have the below configuration for a global schedule with a group, currently only controlling 1 module as I test.  I have 3 times I want to module to not show up, then show the rest of the time.  When I start Magic Mirror the module ends up not showing until the next of the defined "from" times after I launch magic mirror.  So in my below example if I start magic mirror at 12:45, I end up not seeing the module until 19:00, then the module is shown/hidden as expected.  See the below config, and the below log output.  

You can see two of the three conditions have the line "MMM-ModuleScheduler is hiding daytime_scheduler modules" but the middle one simply creates the schedule.  From what I can tell if any of the array conditions prevent showing, its not shown at launch, but then everything works as expected after the next triggered event.

I suppose once I am up and running this isn't a huge deal, but for something that I might only want to run for a small time weekly or monthly that could be more difficult to verify its working as expected.

Config:
//show from 8:00 AM to 11:00 AM, 12:30 PM to 5:00 PM, and from 7:00 PM to 7:00 AM
global_schedule: [
				{from: '0 8 * * *', to: '0 11 * * *', groupClass: 'daytime_scheduler'},
				{from: '30 12 * * *', to: '0 17 * * *', groupClass: 'daytime_scheduler'},
				{from: '0 19 * * *', to: '0 7 * * *', groupClass: 'daytime_scheduler'},
				]

Log:
0|mm       | [06.03.2024 13:08.03.712] [LOG]   MMM-ModuleScheduler is removing all scheduled jobs
0|mm       | [06.03.2024 13:08.03.714] [LOG]   MMM-ModuleScheduler received CREATE_NOTIFICATION_SCHEDULE
0|mm       | [06.03.2024 13:08.03.716] [LOG]   MMM-ModuleScheduler received CREATE_GLOBAL_SCHEDULE
0|mm       | [06.03.2024 13:08.03.718] [LOG]   MMM-ModuleScheduler is creating a global schedule for daytime_scheduler modules using "0 8 * * *" and "0 11 * * *" with dim level undefined
0|mm       | [06.03.2024 13:08.03.777] [LOG]   MMM-ModuleScheduler is hiding daytime_scheduler modules
0|mm       | [06.03.2024 13:08.03.782] [LOG]   MMM-ModuleScheduler has created the global schedule for daytime_scheduler modules
0|mm       | [06.03.2024 13:08.03.783] [LOG]   MMM-ModuleScheduler will next show daytime_scheduler modules at Thu Mar 07 2024 08:00:00 GMT-0800 (Pacific Standard Time)
0|mm       | [06.03.2024 13:08.03.783] [LOG]   MMM-ModuleScheduler will next hide daytime_scheduler modules at Thu Mar 07 2024 11:00:00 GMT-0800 (Pacific Standard Time)
0|mm       | [06.03.2024 13:08.03.783] [LOG]   MMM-ModuleScheduler is creating a global schedule for daytime_scheduler modules using "30 12 * * *" and "0 17 * * *" with dim level undefined
0|mm       | [06.03.2024 13:08.03.793] [LOG]   MMM-ModuleScheduler has created the global schedule for daytime_scheduler modules
0|mm       | [06.03.2024 13:08.03.794] [LOG]   MMM-ModuleScheduler will next show daytime_scheduler modules at Thu Mar 07 2024 12:30:00 GMT-0800 (Pacific Standard Time)
0|mm       | [06.03.2024 13:08.03.795] [LOG]   MMM-ModuleScheduler will next hide daytime_scheduler modules at Wed Mar 06 2024 17:00:00 GMT-0800 (Pacific Standard Time)
0|mm       | [06.03.2024 13:08.03.796] [LOG]   MMM-ModuleScheduler is creating a global schedule for daytime_scheduler modules using "0 19 * * *" and "0 7 * * *" with dim level undefined
0|mm       | [06.03.2024 13:08.03.811] [LOG]   MMM-ModuleScheduler is hiding daytime_scheduler modules
0|mm       | [06.03.2024 13:08.03.813] [LOG]   MMM-ModuleScheduler has created the global schedule for daytime_scheduler modules
0|mm       | [06.03.2024 13:08.03.815] [LOG]   MMM-ModuleScheduler will next show daytime_scheduler modules at Wed Mar 06 2024 19:00:00 GMT-0800 (Pacific Standard Time)
0|mm       | [06.03.2024 13:08.03.817] [LOG]   MMM-ModuleScheduler will next hide daytime_scheduler modules at Thu Mar 07 2024 07:00:00 GMT-0800 (Pacific Standard Time)

**Comment by ianperrin** [comment]
Hi @Fishie20 

Thanks for the detailed report.

I believe you may be encountering the issue described in #7 where modules may appear in a unexpected state if multiple global schedules exist and depending on the time the mirror is started (or the browser refreshed).

Have a look at the issue and the comment, then let me know if you think it matches or you have a different issue.

thanks

**Comment by Fishie20** [comment]
@ianperrin Yes that sure is, I wasn't thinking straight reading that title on the existing bug and didn't click in to check it out further.  I'll close as duplicate!
